env: "local"
server:
  address: "localhost:8888"
  timeout: 5s
  idle_timeout: 30s
db:
  user: "postgres"
  pass: "postgres"
  name: "postgres"
  ssl_mode: "disable"
  port: "5432"
broker:
  client_id: "1"
  servers: "host1:9092,host2:9092"
  acks: "all"